# Generated by Django 5.0.7 on 2024-10-08 17:30

import skinserver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=10, validators=[skinserver.models.length])),
                ('specialties', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Oncology', 'Oncology'), ('Gynecology', 'Gynecology'), ('Nephrology', 'Nephrology'), ('Urology', 'Urology'), ('Liver Transplant', 'Liver Transplant'), ('Gastroenterology', 'Gastroenterology'), ('Pulmonology', 'Pulmonology')], max_length=50)),
            ],
        ),
    ]
