# Generated by Django 5.0.7 on 2024-10-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinserver', '0003_hospital_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='image',
        ),
    ]
