# Generated by Django 5.0.7 on 2024-10-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinserver', '0006_alter_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='specialties',
            field=models.CharField(choices=[('Warts', 'Warts'), ('Melanoma', 'Melanoma'), ('Atopic', 'Atopic'), ('Basal', 'Basal'), ('Melanocytic', 'Melanocytic'), ('Benign', 'Benign'), ('Psoriasis', 'Psoriasis'), ('Seborrheic', 'Seborrheic'), ('Tinea', 'Tinea'), ('Acne', 'Acne'), ('Vitiligo', 'Vitiligo'), ('Chickenpox', 'Chickenpox'), ('Cataract', 'Cataract'), ('Diabetic Retinopathy', 'Diabetic Retinopathy'), ('Glaucoma', 'Glaucoma')], max_length=50),
        ),
    ]
