# Generated by Django 5.0.7 on 2024-10-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinserver', '0008_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
